spring.application.name=TareaProyecto3
spring.datasource.url=jdbc:postgresql://localhost:5432/tareaProyecto3
spring.datasource.username=tareaProyecto3
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true